import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/assets/globals.css";
import { Providers } from "@/app/providers";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="flex items-center justify-center top-0 w-full">
            <div className="flex flex-col items-center justify-between max-w-[1024px] px-6 relative w-full gap-6">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
